### ISSUE TITLE
Error using the visualizer

### ISSUE THREAD

**Issue by BLACK4585** [Alwinator/aw-watcher-utilization#14]
First a update for the Readme: On windows the folder for step 3 of the installation is now `C:\Users\<USER>\AppData\Local\activitywatch\activitywatch`. Then in step 5 you write we should `add aw-table-utilization` to the `aw-qt.toml` file. But in the line below you show that you added `aw-watcher-utilization`. So did I. 
Then, to enable visualization, I added the `aw-watcher-utilization = "C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization"` line, restarted ActivitiyWatch. But then the server doesn't start up anymore, getting this [log](https://pastebin.com/f7JPNiHk).

**Comment by Alwinator** [comment]
@BLACK4585 Thanks for noticing the typos in the docs. I have fixed them now. Regarding the visualization make sure that you have the line
```toml
aw-watcher-utilization = "C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization"
```

in the **aw-server.toml** not aw-qt.toml.

Additionally, because your Windows path includes backslashes try it with a tool raw string:
```toml
[server.custom_static]
aw-watcher-utilization = '''C:\Users\<USER>\AppData\Local\activitywatch\activitywatch\aw-watcher-utilization\visualization'''
```
